name: docs

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::226609089145:role/www-production-GithubRole
          role-session-name: GitHubActions
          role-duration-seconds: 1200

      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'

      - name: mod
        run: go mod download

      - uses: oven-sh/setup-bun@v1

      - name: deploy
        run: |
          bun install
          cd www
          go run ../cmd/sst deploy --stage=production --verbose
